// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN
#include <iostream>
#include "catch.hpp"
#include "main.hpp"

// ===================== T1 — getRow on 3x3 =====================
TEST_CASE("T1.a getRow on 3x3, row=1 (first row)", "[T1]")
{
    int numbers[MAX] = {0, 1, 2, 3, 4, 5, 6, 7, 8};
    int result[MAX];
    getRow(numbers, 3, 3, 1, result);
    REQUIRE(result[0] == 0);
    REQUIRE(result[1] == 1);
    REQUIRE(result[2] == 2);
}
TEST_CASE("T1.b getRow on 3x3, row=2 (middle row)", "[T1]")
{
    int numbers[MAX] = {0, 1, 2, 3, 4, 5, 6, 7, 8};
    int result[MAX];
    getRow(numbers, 3, 3, 2, result);
    REQUIRE(result[0] == 3);
    REQUIRE(result[1] == 4);
    REQUIRE(result[2] == 5);
}
TEST_CASE("T1.c getRow on 3x3, row=3 (last row)", "[T1]")
{
    int numbers[MAX] = {0, 1, 2, 3, 4, 5, 6, 7, 8};
    int result[MAX];
    getRow(numbers, 3, 3, 3, result);
    REQUIRE(result[0] == 6);
    REQUIRE(result[1] == 7);
    REQUIRE(result[2] == 8);
}

// ===================== T2 — getCol on 3x3 =====================
TEST_CASE("T2.a getCol on 3x3, col=1 (first column)", "[T2]")
{
    int numbers[MAX] = {0, 1, 2, 3, 4, 5, 6, 7, 8};
    int result[MAX];
    getCol(numbers, 3, 3, 1, result);
    REQUIRE(result[0] == 0);
    REQUIRE(result[1] == 3);
    REQUIRE(result[2] == 6);
}
TEST_CASE("T2.b getCol on 3x3, col=2", "[T2]")
{
    int numbers[MAX] = {0, 1, 2, 3, 4, 5, 6, 7, 8};
    int result[MAX];
    getCol(numbers, 3, 3, 2, result);
    REQUIRE(result[0] == 1);
    REQUIRE(result[1] == 4);
    REQUIRE(result[2] == 7);
}
TEST_CASE("T2.c getCol on 3x3, col=3 (last column)", "[T2]")
{
    int numbers[MAX] = {0, 1, 2, 3, 4, 5, 6, 7, 8};
    int result[MAX];
    getCol(numbers, 3, 3, 3, result);
    REQUIRE(result[0] == 2);
    REQUIRE(result[1] == 5);
    REQUIRE(result[2] == 8);
}

// ===================== T3 — non-square 4x5 =====================
TEST_CASE("T3.a getRow on 4x5, row=2", "[T3]")
{
    int numbers[MAX] = {6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 16, 17, 18, 19, 20, 11, 12, 13, 14, 15};
    int result[MAX];
    getRow(numbers, 4, 5, 2, result);
    REQUIRE(result[0] == 1);
    REQUIRE(result[1] == 2);
    REQUIRE(result[2] == 3);
    REQUIRE(result[3] == 4);
    REQUIRE(result[4] == 5);
}
TEST_CASE("T3.b getRow on 4x5, row=4 (last row)", "[T3]")
{
    int numbers[MAX] = {6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 16, 17, 18, 19, 20, 11, 12, 13, 14, 15};
    int result[MAX];
    getRow(numbers, 4, 5, 4, result);
    REQUIRE(result[0] == 11);
    REQUIRE(result[4] == 15);
}
TEST_CASE("T3.c getCol on 4x5, col=5 (last col)", "[T3]")
{
    int numbers[MAX] = {6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 16, 17, 18, 19, 20, 11, 12, 13, 14, 15};
    int result[MAX];
    getCol(numbers, 4, 5, 5, result);
    REQUIRE(result[0] == 10);
    REQUIRE(result[1] == 5);
    REQUIRE(result[2] == 20);
    REQUIRE(result[3] == 15);
}

// ===================== T4 — edge: single row / single column =====================
TEST_CASE("T4.a getRow on 1x4 (single-row matrix)", "[T4]")
{
    int numbers[MAX] = {7, 8, 9, 10};
    int result[MAX];
    getRow(numbers, 1, 4, 1, result);
    REQUIRE(result[0] == 7);
    REQUIRE(result[1] == 8);
    REQUIRE(result[2] == 9);
    REQUIRE(result[3] == 10);
}
TEST_CASE("T4.b getCol on 1x4 (single value per column)", "[T4]")
{
    int numbers[MAX] = {7, 8, 9, 10};
    int result[MAX];
    getCol(numbers, 1, 4, 3, result);
    REQUIRE(result[0] == 9);
}
TEST_CASE("T4.c getCol on 4x1 (single-column matrix)", "[T4]")
{
    int numbers[MAX] = {7, 8, 9, 10};
    int result[MAX];
    getCol(numbers, 4, 1, 1, result);
    REQUIRE(result[0] == 7);
    REQUIRE(result[1] == 8);
    REQUIRE(result[2] == 9);
    REQUIRE(result[3] == 10);
}
